version: "3"
services:
  web:
    build: .
    command: ./bin/dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    tty: true
    volumes:
      - ./:/app
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wyda_development
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.0

volumes:
  postgres-data:
